//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptEMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class shift
    {

        [Required(ErrorMessage = " this field is required")]
        public int sno { get; set; }

        [Required(ErrorMessage = " this field is required")]
        public string shiftname { get; set; }

        [Required(ErrorMessage = " this field is required")]

        [DataType(DataType.Date)]
        public Nullable<System.DateTime> created { get; set; }
    }
}
